# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=200)),
                ('flow', models.CharField(max_length=200)),
                ('usid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
            ],
        ),
    ]
