# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-04 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_blockmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_detailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bls', models.CharField(max_length=200)),
                ('fls', models.CharField(max_length=200)),
                ('minimum_capacity', models.IntegerField()),
                ('maximum_capacity', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=200)),
            ],
        ),
    ]
