# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_detailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_detailsmodel',
            name='usids',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel'),
            preserve_default=False,
        ),
    ]
