# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_add_detailsmodel_usids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blk', models.CharField(max_length=100)),
                ('sts', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='add_detailsmodel',
            name='status',
            field=models.CharField(default='OFF', max_length=200),
        ),
    ]
